name: ${name}
description: ${description}
authors:
  - srnyx
website: https://srnyx.com

main: ${mainPackage}.${name}
version: ${version}
api-version: 1.13

softdepend:
  - PlaceholderAPI

commands:
  stopbeinganidiot:
    description: Command for toggling StopBeingAnIdiot
    aliases:
      - sbai
      - stopbeingidiot
    permission: sbai.command

permissions:
  # Command permissions
  sbai.command:
    description: Allows the player to use /stopbeinganidiot
  # Other permissions
  sbai.trigger:
    description: If a player with this permission dies, everyone else dies
    default: true
  sbai.bypass:
    description: Player won't die when everyone else dies
    default: false
